Database performance audit
elmar8287/vet_clinic pull request #5
Opened 2021-11-08 13:31 UTC by elmar8287

- Add an extra column to the owners' table.
- Add requested data to the database.
- Check machine speed by running `explain analyze`.
- Use EXPLAIN ANALYZE on the previous queries.

2021-11-08 16:11 UTC, de-scholar requested changes
Hi @elmar8287 and @Kossi-stack , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>


## Required Changes ♻️
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-08 16:11 UTC, de-scholar commented on schema.sql
>  CREATE TABLE species (
- [x] Adding indexes for FOREIGN KEYS or on columns frequently used in queries is one of the basic solutions for the performance problems would you try it out, this will help you fix the performance issue, because on the screenshots you provided, the second and the last one don't show a significant improve in performance, with the execution time markers, you would need to work a little bit more on this task, and I highly suggest you to try using indexes on foreign keys!

2021-11-09 11:10 UTC, elmar8287 commented on schema.sql
>  CREATE TABLE species (
Done

2021-11-09 11:23 UTC, Emmyn5600 approved these changes
Hi @elmar8287 

Good job👏🏼

## STATUS: APPROVED :muscle::clap:

Congratulations! :tada:
Your project is complete!  It's time to merge it :shipit:
Great work on implementing the changes requested by the previous reviewer.

 #### Optional suggestions
 -  N/A.
 
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### _**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_
------------------------------------------------------------------------------------------------------------------------------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2021-11-09 11:30 UTC, merged